### ISSUE TITLE
sh: CLS: command not found

### ISSUE THREAD

**Issue by PabloAlexis611** [swimmy4days/brainfuck#2]
It looks like the clear screen command being used here is `CLS`, which only works on _Windows_. This could be fixed by using the `clear` command instead, for _macOS_ or _Linux_.

**Comment by PabloAlexis611** [comment]
Ouput error example

<img width="995" alt="image" src="https://user-images.githubusercontent.com/28517429/94389188-2a486900-011d-11eb-95a6-cf73a62666fb.png">

**Comment by swimmy4days** [comment]
Thank You
